// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: find-number-api.proto

package find_number_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FindNumberAPIServiceClient is the client API for FindNumberAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FindNumberAPIServiceClient interface {
	GetNumber(ctx context.Context, in *GetNumberRequest, opts ...grpc.CallOption) (*GetNumberResponse, error)
}

type findNumberAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFindNumberAPIServiceClient(cc grpc.ClientConnInterface) FindNumberAPIServiceClient {
	return &findNumberAPIServiceClient{cc}
}

func (c *findNumberAPIServiceClient) GetNumber(ctx context.Context, in *GetNumberRequest, opts ...grpc.CallOption) (*GetNumberResponse, error) {
	out := new(GetNumberResponse)
	err := c.cc.Invoke(ctx, "/find_number_api.FindNumberAPIService/GetNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FindNumberAPIServiceServer is the server API for FindNumberAPIService service.
// All implementations must embed UnimplementedFindNumberAPIServiceServer
// for forward compatibility
type FindNumberAPIServiceServer interface {
	GetNumber(context.Context, *GetNumberRequest) (*GetNumberResponse, error)
	mustEmbedUnimplementedFindNumberAPIServiceServer()
}

// UnimplementedFindNumberAPIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFindNumberAPIServiceServer struct {
}

func (UnimplementedFindNumberAPIServiceServer) GetNumber(context.Context, *GetNumberRequest) (*GetNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNumber not implemented")
}
func (UnimplementedFindNumberAPIServiceServer) mustEmbedUnimplementedFindNumberAPIServiceServer() {}

// UnsafeFindNumberAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FindNumberAPIServiceServer will
// result in compilation errors.
type UnsafeFindNumberAPIServiceServer interface {
	mustEmbedUnimplementedFindNumberAPIServiceServer()
}

func RegisterFindNumberAPIServiceServer(s grpc.ServiceRegistrar, srv FindNumberAPIServiceServer) {
	s.RegisterService(&FindNumberAPIService_ServiceDesc, srv)
}

func _FindNumberAPIService_GetNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindNumberAPIServiceServer).GetNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/find_number_api.FindNumberAPIService/GetNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindNumberAPIServiceServer).GetNumber(ctx, req.(*GetNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FindNumberAPIService_ServiceDesc is the grpc.ServiceDesc for FindNumberAPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FindNumberAPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "find_number_api.FindNumberAPIService",
	HandlerType: (*FindNumberAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNumber",
			Handler:    _FindNumberAPIService_GetNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "find-number-api.proto",
}
