// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: users-api.proto

package users_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UsersAPIServiceClient is the client API for UsersAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersAPIServiceClient interface {
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
}

type usersAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersAPIServiceClient(cc grpc.ClientConnInterface) UsersAPIServiceClient {
	return &usersAPIServiceClient{cc}
}

func (c *usersAPIServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/users_api.UsersAPIService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersAPIServiceServer is the server API for UsersAPIService service.
// All implementations must embed UnimplementedUsersAPIServiceServer
// for forward compatibility
type UsersAPIServiceServer interface {
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	mustEmbedUnimplementedUsersAPIServiceServer()
}

// UnimplementedUsersAPIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUsersAPIServiceServer struct {
}

func (UnimplementedUsersAPIServiceServer) GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedUsersAPIServiceServer) mustEmbedUnimplementedUsersAPIServiceServer() {}

// UnsafeUsersAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersAPIServiceServer will
// result in compilation errors.
type UnsafeUsersAPIServiceServer interface {
	mustEmbedUnimplementedUsersAPIServiceServer()
}

func RegisterUsersAPIServiceServer(s grpc.ServiceRegistrar, srv UsersAPIServiceServer) {
	s.RegisterService(&UsersAPIService_ServiceDesc, srv)
}

func _UsersAPIService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersAPIServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_api.UsersAPIService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersAPIServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsersAPIService_ServiceDesc is the grpc.ServiceDesc for UsersAPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsersAPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users_api.UsersAPIService",
	HandlerType: (*UsersAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _UsersAPIService_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users-api.proto",
}
